# GitHub Actions Workflow 文件
# 命名为 daily-job.yml 并放置在 .github/workflows/ 目录下

name: Daily Fofa Search

on:
  # 每天世界标准时间 20:00 运行一次
  schedule:
    - cron: "0 20 * * *"
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  run-fofa-script:
    # 运行环境
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      # 检出您的代码库
      uses: actions/checkout@v2
      
    - name: Run Fofa Search Script
      # 更改工作目录到脚本所在位置
      working-directory: ./
      run: |
        # 赋予脚本执行权限
        chmod +x script.sh
        # 执行脚本
        bash ./script.sh
      
    - name: Commit and Push Results
      # 配置 Git 并提交结果文件
      run: |
        # 设置 Git 用户名和邮箱
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # 添加所有新生成的文件
        git add .
        # 提交更改
        git commit -m "chore(workflow): Auto-update fofa search results" || echo "No changes to commit"
        # 推送更改到远程仓库
        git push
